### ISSUE TITLE
Fix on_command_error webhook for DMs

### ISSUE THREAD

**Issue by 4Kaylum** [Voxel-Fox-Ltd/VoxelBotUtils#101]

**Comment by 4Kaylum** [comment]
```
27|gold    | Ignoring exception in on_command_error
27|gold    | Traceback (most recent call last):
27|gold    |   File "/home/kae/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
27|gold    |     await coro(*args, **kwargs)
27|gold    |   File "/home/kae/.local/lib/python3.8/site-packages/voxelbotutils/cogs/error_handler.py", line 284, in on_command_error
27|gold    |     error_text = f"Error `{error}` encountered.\nGuild `{ctx.guild.id}`, channel `{ctx.channel.id}`, user `{ctx.author.id}`\n```\n{ctx.message.content}\n```"
27|gold    | AttributeError: 'NoneType' object has no attribute 'id'
```
