### ISSUE TITLE
keep get this error for stats

### ISSUE THREAD

**Issue by werewolf26** [Voxel-Fox-Ltd/VoxelBotUtils#91]
```python
Traceback (most recent call last):
  File "C:\Users\ow that is the other\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\ow that is the other\AppData\Local\Programs\Python\Python39\lib\site-packages\voxelbotutils\cogs\bot_stats.py", line 78, in stats
    embed.add_field("Coroutines", f"{len([i for i in asyncio.Task.all_tasks() if not i.done()])} running, {len(asyncio.Task.all_tasks())} total.")
AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ow that is the other\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\ow that is the other\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\ow that is the other\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'
```

**Comment by 4Kaylum** [comment]
Apparently `asyncio.Task.all_tasks` was removed in Python 3.9. Its replacement `asyncio.all_tasks` was introduced in 3.7. I primarily use 3.6 - 3.8 so this isn't something that I noticed.

I'll make an update to fix this in a little while if you don't want to PR a fix yourself.
